
import type { Animal } from './definitions';

export const animals: Animal[] = [
  {
    id: '1',
    uid: 'user1',
    userName: 'Rajesh Kumar',
    userPhone: '+919876543211',
    title: 'Healthy HF Cow',
    category: 'Cow',
    breed: 'HF',
    age: '2 years',
    price: 85000,
    location: 'Hyderabad',
    desc: '2nd lactation, 20 liters milk per day. Very healthy and vaccinated.',
    imageUrl: 'https://picsum.photos/seed/cow2/400/300',
    imageHint: 'HF cow',
    status: 'active',
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    featured: true,
  },
  {
    id: '2',
    uid: 'user2',
    userName: 'Suresh Patel',
    userPhone: '+919876543212',
    title: 'Pure Murrah Buffalo',
    category: 'Buffalo',
    breed: 'Murrah',
    age: '3 years',
    price: 95000,
    location: 'Bengaluru',
    desc: 'High-yield Murrah buffalo, calm temperament. Produces 18 liters of milk daily.',
    imageUrl: 'https://picsum.photos/seed/buffalo2/400/300',
    imageHint: 'murrah buffalo',
    status: 'active',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    featured: true,
  },
  {
    id: '3',
    uid: 'user3',
    userName: 'Amit Singh',
    userPhone: '+919876543213',
    title: 'Strong Pair of Oxen',
    category: 'Ox',
    breed: 'Pair Ox',
    age: '4 years',
    price: 120000,
    location: 'Visakhapatnam',
    desc: 'Strong and healthy pair of oxen, great for farming. Well-trained.',
    imageUrl: 'https://picsum.photos/seed/ox1/400/300',
    imageHint: 'ox cart',
    status: 'active',
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: '4',
    uid: 'user1',
    userName: 'Rajesh Kumar',
    userPhone: '+919876543211',
    title: 'Labrador Puppy for Sale',
    category: 'Dog',
    breed: 'Labrador',
    age: '8 weeks',
    price: 15000,
    location: 'Mysuru',
    desc: '8-week old purebred Labrador puppies. Vaccinated and dewormed. Very playful.',
    imageUrl: 'https://picsum.photos/seed/dog2/400/300',
    imageHint: 'labrador dog',
    status: 'active',
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: '5',
    uid: 'user4',
    userName: 'Priya Sharma',
    userPhone: '+919876543214',
    title: 'Sahiwal Cow',
    category: 'Cow',
    breed: 'Sahiwal',
    age: '2.5 years',
    price: 70000,
    location: 'Warangal',
    desc: 'Pure Sahiwal breed, known for heat tolerance and high-quality milk.',
    imageUrl: 'https://picsum.photos/seed/cow3/400/300',
    imageHint: 'sahiwal cow',
    status: 'active',
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    featured: true,
  },
  {
    id: '6',
    uid: 'user5',
    userName: 'Deepak Reddy',
    userPhone: '+919876543215',
    title: 'Country Hens',
    category: 'Hen',
    breed: 'Country Hen',
    age: '6 months',
    price: 500,
    location: 'Guntur',
    desc: 'Free-range country hens, sold per bird. Healthy and active.',
    imageUrl: 'https://picsum.photos/seed/hen2/400/300',
    imageHint: 'country hen',
    status: 'active',
    createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
  },
  {
    id: '7',
    uid: 'user2',
    userName: 'Suresh Patel',
    userPhone: '+919876543212',
    title: 'Persian Cat',
    category: 'Cat',
    breed: 'Persian',
    age: '2 months',
    price: 18000,
    location: 'Hubballi',
    desc: '2-month old male Persian kitten. Litter trained and very affectionate.',
    imageUrl: 'https://picsum.photos/seed/cat1/400/300',
    imageHint: 'persian cat',
    status: 'closed',
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: '8',
    uid: 'user3',
    userName: 'Amit Singh',
    userPhone: '+919876543213',
    title: 'Yorkshire Piglets',
    category: 'Pig',
    breed: 'Yorkshire',
    age: '3 months',
    price: 8000,
    location: 'Vijayawada',
    desc: 'Healthy Yorkshire piglets for sale. Fast-growing breed.',
    imageUrl: 'https://picsum.photos/seed/pig1/400/300',
    imageHint: 'pig farm',
    status: 'active',
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
  },
  {
    id: '9',
    uid: 'mock-user-123',
    userName: 'Demo User',
    userPhone: '+919876543210',
    title: 'Barbari Goat',
    category: 'Goat',
    breed: 'Barbari',
    age: '1 year',
    price: 12000,
    location: 'Karimnagar',
    desc: 'Pure Barbari goat, 1 year old. Ideal for breeding.',
    imageUrl: 'https://picsum.photos/seed/goat1/400/300',
    imageHint: 'white goat',
    status: 'active',
    createdAt: Date.now() - 9 * 24 * 60 * 60 * 1000,
  },
  {
    id: '10',
    uid: 'user4',
    userName: 'Priya Sharma',
    userPhone: '+919876543214',
    title: 'Racing Pigeons',
    category: 'Pigeon',
    breed: 'Homer',
    age: '1.5 years',
    price: 5000,
    location: 'Nalgonda',
    desc: 'Pair of racing homer pigeons. Proven bloodline.',
    imageUrl: 'https://picsum.photos/seed/pigeon1/400/300',
    imageHint: 'white pigeon',
    status: 'active',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
  {
    id: '11',
    uid: 'user5',
    userName: 'Deepak Reddy',
    userPhone: '+919876543215',
    title: 'Deccani Sheep',
    category: 'Sheep',
    breed: 'Deccani',
    age: '2 years',
    price: 7500,
    location: 'Raichur',
    desc: 'Healthy Deccani ram, good for wool and meat.',
    imageUrl: 'https://picsum.photos/seed/sheep1/400/300',
    imageHint: 'white sheep',
    status: 'active',
    createdAt: Date.now() - 11 * 24 * 60 * 60 * 1000,
  },
];


// This is a mock function to add an animal to the in-memory array.
// In a real app, this would be an API call to your backend.
export function addAnimal(animal: Animal) {
  animals.unshift(animal);
}
